version: '3'

services:
  django:
    image: spotify-quickmanager-django
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/django
    ports:
      - "8000:8000"
  vue:
    image: spotify-quickmanager-vuejs
    build: ./frontend
    command: npm run serve
    volumes:
      - ./frontend:/vuejs
    ports:
      - "8080:8080"
    depends_on:
      - django