version: "3"

services:
  vuejs:
    container_name: spqm_dev_vuejs
    build: ./frontend
    command: npm run serve -- --port 80
    ports:
      - 80:80
    volumes:
      - ./frontend:/vuejs
    depends_on:
      - django

  django:
    container_name: spqm_dev_django
    build: ./backend
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    volumes:
      - ./backend:/django
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: spqm_dev_postgres
    image: postgres:latest
    env_file:
      - ./backend/.env
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 15

